{
  imports = [
    ./zotero.nix
    ./git.nix
    ./ranger.nix
    ./kitty.nix
    ./redshift.nix
    ./clipmenu.nix
    #./flameshot.nix
    ./alacritty.nix
    ./nixvim.nix
    ./polybar.nix
    ./bspwm.nix
    ./picom.nix
    ./sxhkd.nix
    ./htop.nix
    ./feh.nix
    #./rofi.nix
    ./firefox.nix
    ./etc.nix
    ./zsh.nix
    ./tmux.nix
  ];
}
