ao=alsa
audio-device=alsa/default
keep-open=yes

vo=gpu-next
profile=high-quality
gpu-api=vulkan

# scale=ewa_lanczos
# scale-blur=0.981251
# dscale=catmull_rom

# dither=error-diffusion
# dither-depth=auto
# error-diffusion=sierra-lite

# scale-antiring=0.5
# dscale-antiring=0.5
# cscale-antiring=0.5

# glsl-shader="~/.config/mpv/glsl/ArtCNN_C4F16.glsl"
# scale=ewa_lanczos
# scale-blur=0.981251

# glsl-shader="~/.config/mpv/glsl/ArtCNN_C4F32_Chroma.glsl"

# --- ui --- 

# Main mpv options
background-color='#282828'   # Base Background (Dark Hard)
osd-back-color='#3c3836'     # Background Soft/Gray
osd-border-color='#3c3836'
osd-color='#ebdbb2'          # Foreground Text
osd-shadow-color='#1d2021'   # Background Darker

# Stats script options
script-opts-append=stats-border_color=928374     # Gray/Neutral
script-opts-append=stats-font_color=ebdbb2      # Foreground Text
script-opts-append=stats-plot_bg_border_color=fabd2f # Yellow (Accent)
script-opts-append=stats-plot_bg_color=282828   # Base Background
script-opts-append=stats-plot_color=fabd2f      # Yellow (Accent)

# UOSC options
script-opts-append=uosc-color=foreground=ebdbb2,foreground_text=ebdbb2,background=1d2021,background_text=ebdbb2,curtain=3c3836,success=b8bb26,error=fb4934
